CREATE NONCLUSTERED INDEX [IX_1] ON [dbo].[CALLS]
(
	[CALLER_ID] ASC,
	[DT] ASC,
	[COST_ID] ASC
)
INCLUDE ([PRICE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)