ALTER TABLE DEPARTMENTS ADD BeginTime TIME NULL
ALTER TABLE DEPARTMENTS ADD EndTime TIME NULL
GO

UPDATE DEPARTMENTS
SET BeginTime = '09:00',
    EndTime = '18:00'
GO

ALTER TABLE DEPARTMENTS ALTER COLUMN BeginTime TIME NOT NULL
ALTER TABLE DEPARTMENTS ALTER COLUMN EndTime TIME NOT NULL
GO